POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Laptop",
  "description": "High performance laptop.",
  "price": 1200,
  "tags": ["tech", "pc", "work"]
}
###
GET http://localhost:3001/products

###
PATCH http://localhost:3001/products/ba08e55a-9c22-4712-acd4-e1206691e0ed
Content-Type: application/json

{
  "name": "Laptoap",
  "description": "High performance laptop.",
  "price": 1200,
  "tags": ["tech", "pc", "work"],
}

###
POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "test",
  "description": "High performance laptop.",
  "price": 1200,
  "tags": ["tech", "pc", "work"]
}

###
GET http://localhost:3000/products?keyword=Lap
