POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "Laptop",
  "description": "High performance laptop.",
  "price": 1200,
  "tags": ["tech", "pc", "work"]
}
###
GET http://localhost:3001/products

###
PATCH http://localhost:3001/products/3ab0cada-ad77-441d-93ae-1e269b2171b1
Content-Type: application/json

{
  "name": "Laptoap",
  "description": "High performance laptop.",
  "price": 1200,
  "tags": ["tech", "pc", "work"]
}

###
POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "test",
  "description": "High performance laptop.",
  "price": 1200,
  "tags": ["tech", "pc", "work"]
}

###
GET http://localhost:3000/products?keyword=Lap

###
GET http://localhost:3100/article
###
POST http://localhost:3100/article
Content-Type: application/json

{
  "name": "test",
  "context": "High performance laptop.",
}

###
GET http://localhost:3100/article/dc79959a-8f68-4ee0-aa5d-cfbc13874d2f

###
GET http://localhost:3100/article/dc79959a-8f68-4ee0-aa5d-cfbc13874d2f/comments

